Task 1

In [65]:
parking_data = [
{"id": "A01", "zone": "A", "status": "occupied", "rate": 100},
{"id": "A02", "zone": "A", "status": "available", "rate": 100},
{"id": "B01", "zone": "B", "status": "occupied", "rate": 80},
{"id": "B02", "zone": "B", "status": "available", "rate": 80},
{"id": "C01", "zone": "C", "status": "available", "rate": 120},
{"id": "C02", "zone": "C", "status": "occupied", "rate": 120}
]

# 1. Display available parking spaces
print("Currently available parking spots:")
for data in parking_data:
    if data["status"] == "available":
        print(f"ID: {data.get('id')}, Zone: {data.get('zone')}, Rate: {data.get('rate')}")

# 2. Unique zones using set
print("Unique zones are: ")
myset=set()
for data in parking_data:
    myset.add(data["zone"])
for zone in myset:
    print(zone)

# 3. Count available and occupied
available=0
occupied=0
for data in parking_data:
    if data["status"] == "available":
        available+=1
    elif data["status"] == "occupied":
        occupied+=1
print(f"Available: {available}, Occupied: {occupied}")

# 4. Calculate cost function
def calculate_cost(rate, hours):
    return rate * hours

# 5. Lambda with sorted to rank by rate
available_spaces=[data for data in parking_data if data["status"] == "available"]
ranked_spaces = sorted(available_spaces, key=lambda  x : x["rate"])
print("Available spaces ranked by hourly rate:")
for spot in ranked_spaces:
    print(f"ID: {spot['id']}, Zone: {spot['zone']}, Rate: {spot['rate']}")

# 6. User input for parking hours
hours = int(input("Enter number of parking hours: "))
print(f"\nEstimated cost for {hours} hour(s):")
for spot in available_spaces:
    cost = calculate_cost(spot["rate"], hours)
    print(f"ID: {spot['id']}, Zone: {spot['zone']}, Cost: {cost}")

# 7. Cheapest available option
cheapest=min(available_spaces,key=lambda x:x["rate"])
print(f"Cheapest available option: ID: {cheapest['id']}, Zone: {cheapest['zone']}, Rate: {cheapest['rate']}")


Currently available parking spots:
ID: A02, Zone: A, Rate: 100
ID: B02, Zone: B, Rate: 80
ID: C01, Zone: C, Rate: 120
Unique zones are: 
B
A
C
Available: 3, Occupied: 3
Available spaces ranked by hourly rate:
ID: B02, Zone: B, Rate: 80
ID: A02, Zone: A, Rate: 100
ID: C01, Zone: C, Rate: 120

Estimated cost for 10 hour(s):
ID: A02, Zone: A, Cost: 1000
ID: B02, Zone: B, Cost: 800
ID: C01, Zone: C, Cost: 1200
Cheapest available option: ID: B02, Zone: B, Rate: 80


Task 2

In [66]:
from functools import reduce
login_data = {
"192.168.1.10": 3,
"192.168.1.21": 17,
"192.168.1.35": 5,
"192.168.1.42": 24,
"192.168.1.51": 11,
"192.168.1.63": 2
}

# 1. Filter suspicious IPs
suspicious_ips=list(filter(lambda ip : login_data[ip] > 10  ,login_data))
print("Suspicious IPs: ")
for ip in suspicious_ips:
    print(f"{ip} → {login_data[ip]} failed attempts")

# 2 & 3. Risk scores using map + lambda
risk_scores=dict(map(lambda ip : (ip,login_data[ip] * 2), suspicious_ips))
print("Risk Scores:")
for ip, score in risk_scores.items():
    print(f"{ip} → Risk Score: {score}")

# 4. Total risk using reduce
total_risk=reduce(lambda acc, score : acc+score , risk_scores.values())
print(f"Total Risk Score: {total_risk}")

# 5. Store in set
suspicious_set = set(suspicious_ips)
print(f"Suspicious IPs Set: {suspicious_set}")

# 6. Highest failed attempts
highest_ip=max(suspicious_ips,key=lambda ip : login_data[ip])
print(f"Highest failed attempts: {highest_ip} → {login_data[highest_ip]} attempts")

# 7 & 8. Classify and security report
def classify_risk(attempts):
    if attempts > 20:
        return "Critical Risk"
    elif attempts >= 16:
        return "High Risk"
    else:
        return "Medium Risk"

print("Security Report:")
for ip in suspicious_ips:
    attempts = login_data[ip]
    level = classify_risk(attempts)
    print(f"{ip} - {attempts} attempts - Risk Score: {risk_scores[ip]} - {level}")
print(f"Total Risk Score: {total_risk}")


Suspicious IPs: 
192.168.1.21 → 17 failed attempts
192.168.1.42 → 24 failed attempts
192.168.1.51 → 11 failed attempts
Risk Scores:
192.168.1.21 → Risk Score: 34
192.168.1.42 → Risk Score: 48
192.168.1.51 → Risk Score: 22
Total Risk Score: 104
Suspicious IPs Set: {'192.168.1.51', '192.168.1.21', '192.168.1.42'}
Highest failed attempts: 192.168.1.42 → 24 attempts
Security Report:
192.168.1.21 - 17 attempts - Risk Score: 34 - High Risk
192.168.1.42 - 24 attempts - Risk Score: 48 - Critical Risk
192.168.1.51 - 11 attempts - Risk Score: 22 - Medium Risk
Total Risk Score: 104


Task 3

In [67]:
import numpy as np

books = np.array([
    [4.5, 120, 80],
    [4.2, 200, 65],
    [4.8, 150, 95],
    [3.9, 300, 55],
    [4.6, 180, 88]
])

# 1. Shape, size, dtype
print(f"Shape: {books.shape}")
print(f"Size: {books.size}")
print(f"Data Type: {books.dtype}")

# 2. Mean of each column
print(f"Mean Rating: {np.mean(books[:, 0])}")
print(f"Mean Views: {np.mean(books[:, 1])}")
print(f"Mean Popularity: {np.mean(books[:, 2])}")


# 3. Min-Max normalization
normalized=np.zeros_like(books)
for i in range(books.shape[1]):
    col=books[:,i]
    normalized[:,i]=(col - col.min()) / (col.max() - col.min())
print("Normalized Array: ")
print(normalized)


# 4. Recommendation score
scores = 0.5 * normalized[:, 0] + 0.2 * normalized[:, 1] + 0.3 * normalized[:, 2]
print(f"Recommendation Scores: {scores}")

# 5 & 6. Rank books highest to lowest
ranked=np.argsort(scores)[::-1]
print("Books ranked by recommendation score:")
for rank, idx in enumerate(ranked):
    print(f"Rank {rank + 1}: Book {idx + 1}, Score: {scores[idx]}")

# 7. Highest recommendation score
best=np.argmax(scores)
print(f"Best book: Book {best + 1}, Score: {scores[best]}")


# 8. Slicing - ratings and popularity separately
print(f"Ratings: {books[:, 0]}")
print(f"Popularity: {books[:, 2]}")

Shape: (5, 3)
Size: 15
Data Type: float64
Mean Rating: 4.4
Mean Views: 190.0
Mean Popularity: 76.6
Normalized Array: 
[[0.66666667 0.         0.625     ]
 [0.33333333 0.44444444 0.25      ]
 [1.         0.16666667 1.        ]
 [0.         1.         0.        ]
 [0.77777778 0.33333333 0.825     ]]
Recommendation Scores: [0.52083333 0.33055556 0.83333333 0.2        0.70305556]
Books ranked by recommendation score:
Rank 1: Book 3, Score: 0.8333333333333333
Rank 2: Book 5, Score: 0.7030555555555554
Rank 3: Book 1, Score: 0.5208333333333335
Rank 4: Book 2, Score: 0.3305555555555557
Rank 5: Book 4, Score: 0.2
Best book: Book 3, Score: 0.8333333333333333
Ratings: [4.5 4.2 4.8 3.9 4.6]
Popularity: [80. 65. 95. 55. 88.]


Task 4

In [68]:
import numpy as np
field_data = [
    {"field": "F1", "temperature": 34, "humidity": 55, "soil_moisture": 28},
    {"field": "F2", "temperature": 29, "humidity": 72, "soil_moisture": 61},
    {"field": "F3", "temperature": 38, "humidity": 48, "soil_moisture": 22},
    {"field": "F4", "temperature": 31, "humidity": 65, "soil_moisture": 47},
    {"field": "F5", "temperature": 36, "humidity": 50, "soil_moisture": 30}
]

# 1. Fields requiring irrigation (soil_moisture < 30)
irrigation = [f["field"] for f in field_data if f["soil_moisture"] < 30]
print(f"Fields needing irrigation: {irrigation}")

# 2. Fields under heat stress (temperature > 35)
heat_stress = [f["field"] for f in field_data if f["temperature"] > 35]
print(f"Fields under heat stress: {heat_stress}")


# 3. Fields with both conditions
both = [f for f in irrigation if f in heat_stress]
print(f"Fields with both conditions: {both}")

# 4. Convert to NumPy matrix
matrix = np.array([[f["temperature"], f["humidity"], f["soil_moisture"]] for f in field_data])
print("Sensor Matrix:")
print(matrix)


# 5. Mean of each sensor
print(f"Mean Temperature: {np.mean(matrix[:, 0])}")
print(f"Mean Humidity: {np.mean(matrix[:, 1])}")
print(f"Mean Soil Moisture: {np.mean(matrix[:, 2])}")

# 6. Variance of each sensor
print(f"Variance Temperature: {np.var(matrix[:, 0])}")
print(f"Variance Humidity: {np.var(matrix[:, 1])}")
print(f"Variance Soil Moisture: {np.var(matrix[:, 2])}")


# 7. Sensor with highest variance
sensors = ["Temperature", "Humidity", "Soil Moisture"]
variances = [np.var(matrix[:, i]) for i in range(3)]
print(f"Highest variance sensor: {sensors[np.argmax(variances)]}")

# 8. Field risk score using normalization
normalized=np.zeros_like(matrix,dtype=float)
for i in range(normalized.shape[1]):
    col=matrix[:,i]
    normalized[:,i]=(col-col.min()) / (col.max() - col.min())   
risk_scores = 0.4 * normalized[:, 0] + 0.2 * normalized[:, 1] + 0.4 * (1 - normalized[:, 2])


# 9. Rank fields highest to lowest risk
ranked = np.argsort(risk_scores)[::-1]
print("Fields ranked by risk:")
for rank, idx in enumerate(ranked):
    print(f"Rank {rank + 1}: {field_data[idx]['field']}, Risk Score: {risk_scores[idx]}")

# 10. Recommendations
print("Recommendations:")
for idx in ranked:
    score = risk_scores[idx]
    if score > 0.7:
        level = "High Risk - Immediate inspection required"
    elif score > 0.4:
        level = "Medium Risk - Monitor field"
    else:
        level = "Low Risk - Normal condition"
    print(f"{field_data[idx]['field']}: {level}")

Fields needing irrigation: ['F1', 'F3']
Fields under heat stress: ['F3', 'F5']
Fields with both conditions: ['F3']
Sensor Matrix:
[[34 55 28]
 [29 72 61]
 [38 48 22]
 [31 65 47]
 [36 50 30]]
Mean Temperature: 33.6
Mean Humidity: 58.0
Mean Soil Moisture: 37.6
Variance Temperature: 10.64
Variance Humidity: 83.6
Variance Soil Moisture: 205.84
Highest variance sensor: Soil Moisture
Fields ranked by risk:
Rank 1: F3, Risk Score: 0.8
Rank 2: F5, Risk Score: 0.6457264957264958
Rank 3: F1, Risk Score: 0.619017094017094
Rank 4: F4, Risk Score: 0.37414529914529915
Rank 5: F2, Risk Score: 0.2
Recommendations:
F3: High Risk - Immediate inspection required
F5: Medium Risk - Monitor field
F1: Medium Risk - Monitor field
F4: Low Risk - Normal condition
F2: Low Risk - Normal condition


Task 5

In [69]:
import numpy as np

# Part A: Route Representation

# 1. Tuples for coordinates
stops = [
("Stop A", (33.6425, 73.1730)),
("Stop B", (33.6500, 73.1600)),
("Stop C", (33.6550, 73.1500)),
("Stop D", (33.6600, 73.1400)),
("Stop E", (33.6650, 73.1300))
]

routes = [
["Stop A", "Stop B", ["Stop C", "Stop D"]],
["Stop A", ["Stop E"]]
]

# 2. Dictionary mapping stop name to coordinates
stop_dict = {}
for stop, coords in stops:
    stop_dict[stop] = coords
print("Stop Dictionary:")
for name, coords in stop_dict.items():
    print(f"{name}: {coords}")

# Part B: Route Exploration

# 3. Set for visited stops
visited=set()

# 4. Check if stop is visited
def is_visited(stop):
    return stop in visited

# 5. Add visited stop
def visit_stop(stop):
    visited.add(stop)

# Part C: Nested Route Processing

# 6. Recursive flatten function
def flatten_route(routes):
    result=[]
    for route in routes:
        if isinstance(route,list):
            result.extend(flatten_route(route))
        else:
            result.append(route)
    return result


# Part D: Distance Calculation

# 7. Euclidean distance between two points
def calculate_distance(point1, point2):
    return np.sqrt((point2[0] - point1[0])**2 + (point2[1] - point1[1])**2)

# Part E: NumPy Analysis

# 8. Store coordinates in NumPy array
coords = np.array([coord for _, coord in stops])

# 9. Mean lat, mean lon, min lat, max lat
print(f"Mean Latitude: {np.mean(coords[:, 0])}")
print(f"Mean Longitude: {np.mean(coords[:, 1])}")
print(f"Min Latitude: {np.min(coords[:, 0])}")
print(f"Max Latitude: {np.max(coords[:, 0])}")

# 10. Distance between consecutive stops
distances = []
for i in range(len(coords) - 1):
    d = calculate_distance(coords[i], coords[i + 1])
    distances.append(d)
    print(f"{stops[i][0]} → {stops[i+1][0]}: {d}")


# Part F: Route Decision

# 11. Closest pair of consecutive stops
min_idx = np.argmin(distances)
print(f"Closest pair: {stops[min_idx][0]} → {stops[min_idx+1][0]}, Distance: {distances[min_idx]}")

# 12. Display flattened route
flat_route = flatten_route(routes)
print(f"Flattened Route: {flat_route}")

# 13. Display visited stops
for stop in flat_route:
    if not is_visited(stop):
        visit_stop(stop)
print(f"Visited Stops: {visited}")

# 14. Route statistics
print(f"Total stops: {len(stops)}")
print(f"Unique visited: {len(visited)}")
print(f"Total distances: {distances}")
print(f"Shortest distance: {min(distances)}")
print(f"Longest distance: {max(distances)}")


Stop Dictionary:
Stop A: (33.6425, 73.173)
Stop B: (33.65, 73.16)
Stop C: (33.655, 73.15)
Stop D: (33.66, 73.14)
Stop E: (33.665, 73.13)
Mean Latitude: 33.6545
Mean Longitude: 73.1506
Min Latitude: 33.6425
Max Latitude: 33.665
Stop A → Stop B: 0.015008331019808306
Stop B → Stop C: 0.011180339887491958
Stop C → Stop D: 0.01118033988750149
Stop D → Stop E: 0.011180339887504668
Closest pair: Stop B → Stop C, Distance: 0.011180339887491958
Flattened Route: ['Stop A', 'Stop B', 'Stop C', 'Stop D', 'Stop A', 'Stop E']
Visited Stops: {'Stop D', 'Stop E', 'Stop A', 'Stop B', 'Stop C'}
Total stops: 5
Unique visited: 5
Total distances: [np.float64(0.015008331019808306), np.float64(0.011180339887491958), np.float64(0.01118033988750149), np.float64(0.011180339887504668)]
Shortest distance: 0.011180339887491958
Longest distance: 0.015008331019808306
